<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-09-01 05:51
 * @usage: C::t('#tingsuan#tingsuan_exam')->fun();
 **/
class table_tingsuan_exam extends discuz_table
{
    public function __construct() {
        $this->_table = 'tingsuan_exam';
        $this->_pk = 'id';
        parent::__construct();
    }

    // 根据主键获取记录
    public function get_by_pk($id) {
        $sql = "SELECT * FROM ".DB::table($this->_table)." WHERE ".$this->_pk."='$id'";
        return DB::fetch_first($sql);
    }

    // 获取全部
    public function getOptions() {   
        $sql = "SELECT id as value,name as text FROM ".DB::table($this->_table)." WHERE isdel=0";
        return DB::fetch_all($sql);
    }

    // 创建exam
    public function create($template_id,$exam_count,$title)
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $ctime = date('Y-m-d H:i:s');
        $record = array (
            'template_id' => $template_id,
            'exam_count' => $exam_count,
            'title' => $title,
            'uid' => $uid,
            'begin_time' => date('Y-m-d H:i:s'),
            'ctime' => $ctime,
            'status' => 1,
            'isdel' => 0,
        );
        return $this->insert($record,true);
    }/*}}}*/


    // 查询接口
    public function queryMine()
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $return = array(
            "totalProperty" => 0,
            "root" => array(),
        );
        $sort  = tingsuan_validate::getOPParameter('sort','sort','string',1024,'begin_time');
        $dir   = tingsuan_validate::getOPParameter('dir','dir','string',1024,'DESC');
        $start = tingsuan_validate::getOPParameter('start','start','integer',1024,0);
        $limit = tingsuan_validate::getOPParameter('limit','limit','integer',1024,20);
        $where = "a.uid='$uid' AND a.status=2 AND a.isdel=0";
        $table = DB::table($this->_table);
        $sql = <<<EOF
SELECT SQL_CALC_FOUND_ROWS 
a.id,a.title,a.exam_count as examCount,a.begin_time as beginTime,
a.accuracy
FROM $table as a
WHERE $where
ORDER BY $sort $dir
LIMIT $start,$limit
EOF;
        $return["root"] = DB::fetch_all($sql);
        $row = DB::fetch_first("SELECT FOUND_ROWS() AS total");
        $return["totalProperty"] = $row["total"];
        return $return;
    }/*}}}*/

    // 保存记录
    public function save()
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $id = tingsuan_validate::getNCParameter('id','id','integer');
        $record = array (
            'begin_time' => tingsuan_validate::getNCParameter('begin_time','begin_time','string',1024),
            'end_time' => tingsuan_validate::getNCParameter('end_time','end_time','string',1024),
        ); 
        if ($id==0) {
            $record['ctime'] = date('Y-m-d H:i:s');
            return $this->insert($record);
        } else {
            return $this->update($id,$record);
        }
    }/*}}}*/

    // 删除记录
    public function remove()
    {/*{{{*/
        $id = tingsuan_validate::getNCParameter('id','id','integer');
        return $this->update($id,array('isdel'=>1));
    }/*}}}*/

    // 设置保存
    public function setEnable()
    {/*{{{*/
        $id = tingsuan_validate::getNCParameter('id','id','integer');
        $enable = tingsuan_validate::getNCParameter('enabled','enabled','integer');
        return $this->update($id,array('enabled'=>$enable));
    }/*}}}*/


}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
