<?php
if(!defined('IN_DISCUZ')) {
    exit('Access Denied');
}
/**
 * generated by mengma
 * @create: 2018-09-01 06:23
 * @usage: C::t('#tingsuan#tingsuan_exam_record')->fun();
 **/
class table_tingsuan_exam_record extends discuz_table
{
    public function __construct() {
        $this->_table = 'tingsuan_exam_record';
        $this->_pk = 'id';
        parent::__construct();
    }

    // 根据主键获取记录
    public function get_by_pk($id) {
        $sql = "SELECT * FROM ".DB::table($this->_table)." WHERE ".$this->_pk."=''";
        return DB::fetch_first($sql);
    }

    // 获取全部
    public function getOptions() {   
        $sql = "SELECT id as value,name as text FROM ".DB::table($this->_table)." WHERE isdel=0";
        return DB::fetch_all($sql);
    }

    // 获取测试的全部题目列表
    public function getByExamId($examId)
    {
        $sql = "SELECT id,question_title as questionTitle,express,question_options,".
                    "right_answer,user_answer,status ".
               "FROM ".DB::table($this->_table)." ".
               "WHERE exam_id='$examId' AND isdel=0 ".
               "ORDER BY display_order ASC";
        $res = DB::fetch_all($sql);
        foreach ($res as &$row) {
            $row['questionOptions'] = json_decode($row['question_options'],true);
            $row['express'] = json_decode($row['express'],true);
            unset($row['question_options']);
        }
        return $res;
    }

    // 批量保存
    public function batSave($examId, array &$expresses)
    {/*{{{*/
        if (empty($expresses) || $examId==0) return;
        global $_G;
        $uid = $_G['uid'];
        $vals = array();
        $m_exam = C::m('#tingsuan#tingsuan_exam');
        $display_order = 0;
        $ctime = date('Y-m-d H:i:s');
        foreach ($expresses as $express) {
            $title = implode('',$express);
            $expressJson = json_encode($express);
            $right_answer = $m_exam->calculateArithmetic($express);
            $question_options = array (
                $right_answer, 1+$right_answer, $right_answer-1, $right_answer+2
            );
            shuffle($question_options);
            $questionJson = json_encode($question_options);
            ++$display_order;
            $status=0;
            
            $data = array (
                'exam_id' => $examId,
                'question_title' => $title,
                'express' => $expressJson,
                'question_options' => $questionJson,
                'right_answer' => $right_answer,
                'status' => $status,
                'display_order' => $display_order,
                'uid' => $uid,
                'ctime' => $ctime,
            );
            $this->insert($data);
            /*
            $vals[] = "('$examId','$title','$expressJson','$questionJson','$right_answer',".
                       "'$status','$display_order','$uid','$ctime')";
            */
        }
/*
        $table = DB::table($this->_table);
        $sql = "INSERT INTO $table ".
               "(`exam_id`,`question_title`,`express`,`question_options`,`right_answer`,`status`,`display_order`,`uid`,`ctime`) VALUES ".
               implode(',',$vals);
        return DB::query($sql);
*/
    }/*}}}*/


    // 查询接口
    public function query()
    {/*{{{*/
        $return = array(
            "totalProperty" => 0,
            "root" => array(),
        );
        $key   = tingsuan_validate::getNCParameter('key','key','string');
        $sort  = tingsuan_validate::getOPParameter('sort','sort','string',1024,'id');
        $dir   = tingsuan_validate::getOPParameter('dir','dir','string',1024,'DESC');
        $start = tingsuan_validate::getOPParameter('start','start','integer',1024,0);
        $limit = tingsuan_validate::getOPParameter('limit','limit','integer',1024,20);
        $where = "isdel=0";
        if ($key!="") $where.=" AND (name like '%$key%')";
        $table = DB::table($this->_table);
        $sql = <<<EOF
SELECT SQL_CALC_FOUND_ROWS a.*
FROM $table as a
WHERE $where
ORDER BY $sort $dir
LIMIT $start,$limit
EOF;
        $return["root"] = DB::fetch_all($sql);
        $row = DB::fetch_first("SELECT FOUND_ROWS() AS total");
        $return["totalProperty"] = $row["total"];
        return $return;
    }/*}}}*/

    // 保存记录
    public function save()
    {/*{{{*/
        global $_G;
        $uid = $_G['uid'];
        $id = tingsuan_validate::getNCParameter('id','id','integer');
        $record = array (
            'exam_id' => tingsuan_validate::getNCParameter('exam_id','exam_id','integer',1024),
            'question_title' => tingsuan_validate::getNCParameter('question_title','question_title','string',1024),
            'express' => tingsuan_validate::getNCParameter('express','express','string',1024),
            'question_options' => tingsuan_validate::getNCParameter('question_options','question_options','string',1024),
            'user_answer' => tingsuan_validate::getNCParameter('user_answer','user_answer','string',1024),
            'right_answer' => tingsuan_validate::getNCParameter('right_answer','right_answer','string',1024),
            'status' => tingsuan_validate::getNCParameter('status','status','integer',1024),
            'display_order' => tingsuan_validate::getNCParameter('display_order','display_order','integer',1024),
            'begin_time' => tingsuan_validate::getNCParameter('begin_time','begin_time','string',1024),
            'end_time' => tingsuan_validate::getNCParameter('end_time','end_time','string',1024),
        ); 
        if ($id==0) {
            $record['ctime'] = date('Y-m-d H:i:s');
            return $this->insert($record);
        } else {
            return $this->update($id,$record);
        }
    }/*}}}*/

    // 删除记录
    public function remove()
    {/*{{{*/
        $id = tingsuan_validate::getNCParameter('id','id','integer');
        return $this->update($id,array('isdel'=>1));
    }/*}}}*/

    // 设置保存
    public function setEnable()
    {/*{{{*/
        $id = tingsuan_validate::getNCParameter('id','id','integer');
        $enable = tingsuan_validate::getNCParameter('enabled','enabled','integer');
        return $this->update($id,array('enabled'=>$enable));
    }/*}}}*/


}
// vim600: sw=4 ts=4 fdm=marker syn=php
?>
